"""
Categorize Work Chronicles comics by title using keyword matching.

Each category has a set of keywords/phrases. A post is assigned to the
category with the highest keyword match count. If no keywords match,
the post falls into "Office Culture" as the default catch-all.
"""

CATEGORIES = {
    "Meetings": {
        "icon": "📅",
        "description": "Meeting culture, standups, presentations, and calls",
        "keywords": [
            "meeting",
            "standup",
            "stand-up",
            "daily standup",
            "sync up",
            "sync-up",
            "townhall",
            "town hall",
            "could have been an email",
            "presentation",
            "slide",
            "slides",
            "check-in",
            "check in",
            "take that offline",
            "offline",
            "virtual meeting",
            "turn on your cameras",
            "biweekly",
            "agenda",
            "404 - meeting agenda",
            "meeting agenda not found",
            "so any questions",
            "any questions",
        ],
    },
    "Productivity": {
        "icon": "⚡",
        "description": "Time management, efficiency hacks, and doing more with less",
        "keywords": [
            "productive",
            "productivity",
            "time management",
            "deep work",
            "80-20",
            "pareto",
            "efficiency",
            "focus area",
            "fast and slow",
            "high leverage",
            "zoom out",
            "do your best work",
            "workload",
            "how to deliver",
            "4 easy steps",
            "simple trick",
            "ship faster",
            "getting work done",
            "solving problems at work",
            "problem solving",
            "work prioritis",
            "high leverage work",
            "solving for low productivity",
        ],
    },
    "Management & Leadership": {
        "icon": "👔",
        "description": "Managers, decisions, priorities, and leadership principles",
        "keywords": [
            "management",
            "manager",
            "leadership",
            "leader",
            "decision",
            "delegat",
            "cxo",
            "chief",
            "leadership principles",
            "chief decision maker",
            "accountability",
            "ownership",
            "absolute ownership",
            "show ownership",
            "bureaucracy",
            "bureaucracy trap",
            "micromanag",
            "root of all micromanagement",
            "my previous org",
            "old org",
            "previous org",
            "not my problem",
            "master of my fate",
            "refactor ego",
            "poor performance",
            "poor decisions",
            "understaffed",
            "overworked",
            "attrition",
            "layoff",
            "nobody wants to work",
            "trust",
            "above and beyond",
            "reward for good work",
            "the reward",
            "employee satisfaction",
            "fixing employee satisfaction",
            "adding more people to a project",
            "hiring 2 to replace",
            "workload of two",
            "no good work goes unpunished",
        ],
    },
    "Interviews & Hiring": {
        "icon": "🎯",
        "description": "Interview questions, resumes, hiring, and exit interviews",
        "keywords": [
            "interview",
            "hiring",
            "hire",
            "resume",
            "cv",
            "candidate",
            "why are you leaving",
            "where do you see yourself",
            "greatest strength",
            "greatest weakness",
            "tell me about a time",
            "behavioral",
            "exit interview",
            "onboarding",
            "new employee",
            "showing the new employee",
            "credential",
            "len(resume)",
            "culture fit",
            "team fitment",
            "recruit",
            "ace your interview",
            "how to ace",
            "interviewing vs",
            "the actual job",
            "the interview vs",
            "honest behavioral",
            "honest answers",
            "junior vs senior",
            "what do you do for a living",
            "me explaining what i do",
            "why do you want to work here",
            "so, why do you want to work",
        ],
    },
    "Feedback & Reviews": {
        "icon": "💬",
        "description": "Performance reviews, feedback loops, and employee surveys",
        "keywords": [
            "feedback",
            "performance review",
            "anonymous employee survey",
            "feedback sandwich",
            "gratitude",
            "earn gratitude",
            "rating",
            "ratings",
            "calibration",
            "just checking in",
            "checking in",
            "ask for feedback",
            "when you ask for feedback",
            "direct and clear feedback",
            "clear and direct feedback",
            "progressive feedback",
            "leadership feedback",
            "feedback based",
            "honest review",
            "incorporating all feedback",
            "you're doing a great job",
            "you are doing a great job",
        ],
    },
    "Agile & Process": {
        "icon": "🔄",
        "description": "Sprints, backlog, agile, and process bureaucracy",
        "keywords": [
            "agile",
            "sprint",
            "backlog",
            "scrum",
            "roadmap",
            "kanban",
            "put it in the backlog",
            "added to the roadmap",
            "we are agile",
            "sprint review",
            "process",
            "workflow",
            "user stories",
            "user story",
            "move fast and break things",
            "move fast break things",
            "fast paced",
            "fast-paced",
            "sprints",
            "agile mind games",
        ],
    },
    "Work-Life Balance": {
        "icon": "🏖️",
        "description": "Burnout, long hours, weekends, and vacation myths",
        "keywords": [
            "long hours",
            "work long hours",
            "burnout",
            "weekend",
            "vacation",
            "time off",
            "ooo",
            "out of office",
            "work-life",
            "work life",
            "mental health",
            "monday",
            "mondays",
            "friday",
            "fridays",
            "hate mondays",
            "monday blues",
            "eat sleep work repeat",
            "eat. sleep. work. repeat.",
            "dream job",
            "dream of vacation",
            "never sleep",
            "35-minute lunch",
            "your lunch matters",
            "flexible working",
            "flexible working hours",
            "don't ruin your weekend",
            "take care of your health",
            "dream. i only dream of vacations",
            "vacation refresher myth",
            "take care of your health",
            "workload and mental health",
        ],
    },
    "Communication": {
        "icon": "✉️",
        "description": "Emails, chat, jargon, and corporate speak",
        "keywords": [
            "email",
            "chat",
            "jargon",
            "excuse my jargon",
            "heavy jargon",
            "overcommunicat",
            "over-communicat",
            "communication",
            "typing...",
            "nohello",
            "answer first",
            "details later",
            "get to the point",
            "sweet talk",
            "spin the story",
            "half truth",
            "half-truth",
            "rhetorical",
            "small talk",
            "follow up",
            "follow through",
            "did you get my email",
            "inbox",
            "inbox zero",
            "phone call",
            "phone calls",
            "picking up phone",
            "cold call",
            "cold calls",
            "ask for help",
            "how to ask for help",
            "figure it out vs",
            "nohello",
            "always be overcommunicating",
            "always be over-communicating",
        ],
    },
    "Compensation & Promotions": {
        "icon": "💰",
        "description": "Salary, raises, negotiations, and promotion games",
        "keywords": [
            "salary",
            "compensation",
            "raise",
            "pay hike",
            "promotion",
            "promote",
            "appraisal",
            "negotiat",
            "stretch assignment",
            "promotion driven",
            "fungible",
            "fungibility",
            "fungible resource",
            "budget",
            "don't have the budget",
            "we don't have the budget",
            "bonus",
            "inflation",
            "make good money",
            "finally make good money",
            "salary negotiation",
            "common salary",
            "getting a raise",
            "top secret raise",
            "no promotion",
            "negotiation stalemate",
            "perks of the job",
            "job perks",
            "record profits",
            "cost optimis",
            "cost optimiz",
            "i finally make",
            "pay",
        ],
    },
    "AI & Technology": {
        "icon": "🤖",
        "description": "AI, automation, coding, and tech trends",
        "keywords": [
            " ai ",
            "ai won't",
            "ai will",
            "ai chronicles",
            "artificial intelligence",
            "automate all",
            "automation",
            "vibe code",
            "vibe coding",
            "intelligent ai",
            "can't we just use ai",
            "state-of-the-art",
            "ai developers",
            "coding",
            "commit message",
            "meaningful commit",
            "refactor",
            "fix all the bugs",
            "bug reduction",
            "clean and optimized code",
            "working code",
            "keyboard shortcut",
            "10x engineer",
            "build vs buy",
            "cutting edge",
            "cutting-edge",
            "it security",
            "access denied",
            "feature request",
            "writing commit",
            "automate",
            "why ai won't",
            "ai won't replace",
        ],
    },
    "Estimates & Deadlines": {
        "icon": "⏰",
        "description": "ETAs, timelines, delivery pressure, and scope",
        "keywords": [
            "eta",
            "deadline",
            "estimate",
            "sacred estimate",
            "i need it yesterday",
            "urgent",
            "when you get a chance",
            "should be easy",
            "easy to do",
            "guesstimate",
            "fast good cheap",
            "good fast cheap",
            "good. fast. cheap.",
            "trade-off",
            "tradeoff",
            "trade off",
            "evaluating trade",
            "successful tradeoff",
            "on priority",
            "we need it on priority",
            "need it on priority",
            "top priority",
            "everything is high priority",
            "stretch for the deadline",
            "eta of the eta",
            "eta for the eta",
            "so what's the eta",
            "what's the eta",
            "scope",
            "scope creep",
            "meet the deadline",
        ],
    },
    "Data & Metrics": {
        "icon": "📊",
        "description": "Data-driven decisions, KPIs, and measurement obsession",
        "keywords": [
            "data driven",
            "data-driven",
            "data informed",
            "data vs",
            "data insight",
            "data loophole",
            "backing your idea",
            "measure it",
            "improve it",
            "impact measurement",
            "intuition",
            "data vs. intuition",
            "data vs insight",
            "okr dilemma",
            "okr",
            "decibel-based",
            "performance calibration",
            "we are data-driven",
            "reminder to measure",
            "measure the right metrics",
            "data backing",
        ],
    },
    "Career Growth": {
        "icon": "📈",
        "description": "Skills, learning, ambition, and career planning",
        "keywords": [
            "5 year plan",
            "five-year plan",
            "five year plan",
            "where do you see yourself in 5",
            "career",
            "ambition",
            "keep learning",
            "improving your craft",
            "learning opportunity",
            "learning patience",
            "learn new things",
            "get inspired",
            "long term thinking",
            "thinking on your feet",
            "thinking on my feet",
            "comfort zone",
            "shake things up",
            "be bold",
            "risk-taking",
            "take risks",
            "mindset",
            "keep calm",
            "carpe diem",
            "impostor syndrome",
            "imposter syndrome",
            "full potential",
            "full responsibility",
            "courage to speak up",
            "speak up",
            "time to cut your losses",
            "work projects vs. personal",
            "work projects and personal",
            "inside-the-box brainstorm",
            "personal projects",
            "get inspired",
            "start your own business",
            "entrepreneur",
            "learn. sleep. work",
            "skill",
            "skills",
            "expertise",
            "range of emotions",
            "putting in papers",
            "giving notice",
            "putting things in perspective",
            "deep breaths",
        ],
    },
    "Client & Sales": {
        "icon": "🤝",
        "description": "Customers, clients, sales calls, and requirements",
        "keywords": [
            "client",
            "customer",
            "sales",
            "user need",
            "user needs",
            "engineer on a sales",
            "sales call",
            "signed a new client",
            "understanding client",
            "customer-centric",
            "client requirement",
            "user stories for clarity",
        ],
    },
    "Office Culture": {
        "icon": "🏢",
        "description": "Corporate absurdity, quirks, and workplace humor",
        "keywords": [
            "culture",
            "perks",
            "morale",
            "team",
            "welcome to hell",
            "bring your true self",
            "safe space",
            "we care about you",
            "we value you",
            "we encourage",
            "we embrace",
            "dogfooding",
            "hype",
            "hype it up",
            "amnesia",
            "memory error",
            "welcome to the club",
            "participate in the upside",
            "bring me solutions",
            "don't bring me problems",
            "yes man",
            "never be a yes man",
            "linkedin",
            "humblebrag",
            "cool thing to say",
            "bold claim",
            "magical projection",
            "superiority complex",
            "halo effect",
            "cherry picking",
            "cherry pick",
            "toxic culture",
            "cultural fit",
            "selective storytelling",
        ],
    },
}

# Category used when no keywords match strongly enough.
DEFAULT_CATEGORY = "Office Culture"

# Posts that are announcements, milestones, or meta content.
ANNOUNCEMENT_KEYWORDS = [
    "announcement",
    "2025 calendar",
    "2026 calendar",
    "order the",
    "beat the holiday",
    "turns 1",
    "turns 2",
    "turns 3",
    "turns 4",
    "turns 5",
    "top comics of",
    "april fools",
    "newsletter",
    "rewindwednesdays",
    "#rewind",
    "happy new year",
    "coming soon to a chat",
]


def _score_title(title: str, keywords: list[str]) -> int:
    """Count how many keywords match the lowercased title."""
    lower = title.lower()
    return sum(1 for kw in keywords if kw in lower)


def categorize(title: str) -> str:
    """Return the best-matching category for a comic title.

    Checks announcement keywords first, then scores against every category
    and picks the highest. Ties go to whichever category appears first in
    CATEGORIES (insertion order).
    """
    lower = title.lower()

    for kw in ANNOUNCEMENT_KEYWORDS:
        if kw in lower:
            return "Announcements"

    best_cat = DEFAULT_CATEGORY
    best_score = 0

    for cat_name, cat_info in CATEGORIES.items():
        score = _score_title(title, cat_info["keywords"])
        if score > best_score:
            best_score = score
            best_cat = cat_name

    return best_cat


def categorize_posts(posts: list[dict]) -> list[dict]:
    """Add/overwrite the 'category' field on each post dict. Returns the list."""
    for post in posts:
        post["category"] = categorize(post.get("title", ""))
    return posts


def get_category_summary(posts: list[dict]) -> dict[str, int]:
    """Return {category: count} sorted descending by count."""
    summary: dict[str, int] = {}
    for post in posts:
        cat = post.get("category", DEFAULT_CATEGORY)
        summary[cat] = summary.get(cat, 0) + 1
    return dict(sorted(summary.items(), key=lambda x: x[1], reverse=True))
